### PR TITLE
Newman Hangman Pseudocode

### PR DESCRIPTION
**Pull request by Urban158**
Newman Hangman Pseudocode

https://github.com/loyno-cosc-a211-201901/cosc-a211-term-project-Urban158/compare/B-files-with-pseudocode-comments...master

### CODE REVIEW

**Comment by Urban158** [comment]
https://github.com/loyno-cosc-a211-201901/cosc-a211-term-project-Urban158/pull/2

**Comment by Urban158** [comment]
https://github.com/loyno-cosc-a211-201901/cosc-a211-term-project-Urban158/pull/2

**Comment by ADWolfe-LoyNO** [comment]
Derris,

you have a good start.  Your gallows functions in NewmanGallowTest.cpp look like they are on the right track.

Please start putting the trace messages in so that you can see the program "running".

- Prof Andrew

**Comment by Urban158** [comment]
Got it thanks!!

**Pull request closed without merging**
